### PR TITLE
Update pty-shell dependencies

### PR DESCRIPTION
**Pull request by hanachin**
0.1.2 matches 0.1.3, PtyProxy renamed to PtyShell in pty-shell v0.1.3, it breaks build.

### CODE REVIEW

**Comment by hibariya** [comment]
> 0.1.2 matches 0.1.3

Thank you for the Pull Request! I didn't know about that :dizzy_face:
The new version (0.0.7) has been published :rocket:

**Comment by hanachin** [comment]
When I clean install hokaido, I saw pty-shell 0.1.3 in Cargo.lock, very suprised.
I've found a test case that 0.1.2 matches 0.1.3 in semver which Cargo uses.
https://github.com/steveklabnik/semver/blob/4ff8d6e2d33b90d002517b69f23713613591019a/src/version_req.rs#L869,L877

**Comment by hanachin** [comment]
Thank you for release :rocket: 

``` console
% cargo install hokaido
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading hokaido v0.0.7
   Compiling hokaido v0.0.7
  Installing /Users/sei/.cargo/bin/hokaido
be sure to add `/Users/sei/.cargo/bin` to your PATH to be able to run the installed binaries
```

**Comment by hibariya** [comment]
Yay :raising_hand: Thank you for your valuable information about versioning.

**Pull request merged**
